# {"networks": {"stack-php": {"driver": ..., "ipam": {
#    "config": [
#       {
#           "subnet": ..., 
#           "gateway": ...
#       },
#       {...}
#    ]
#}}}}


networks:
  stack-php:
    # fixer le nom du réseau
    name: stack-php
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
#       - ...

## on doit déclarer les volumes nommés !!!
volumes:
  db_data:
   # fixer le nom du volume
   name: db_data

services:
  stack-php-nginx:
    # fixer le nom des conteneurs
    container_name: stack-php-nginx
    image: nginx:1.27.1-alpine-slim
    restart: unless-stopped
    networks:
      - stack-php
    ports:
      - 8080:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/vhost.conf:ro
  
  stack-php-8.3-fpm:
    container_name: stack-php-8.3-fpm
    image: bitnami/php-fpm:8.3-debian-12
    restart: unless-stopped
    networks:
      - stack-php
    volumes:
      - ./index.php:/srv/index.php:ro

  stack-php-mariadb:
    container_name: stack-php-mariadb
    image: mariadb:11.5
    restart: unless-stopped
    networks:
      - stack-php
    env_file:
      - .env
    # environment:
    #   - MARIADB_USER=test
    volumes:
      - ./mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql:ro
      - db_data:/var/lib/mysql:Z
