networks:
  poc-php:
    name: poc-php
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1

volumes:
  db_data:
   name: db_data
  nfs-vol-nginx:
    name: nfs-vol-nginx
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.30,ro
      device: :/mnt/nfs-dir/nginx-conf.d
  nfs-vol-php:
    name: nfs-vol-php
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.30,ro
      device: :/mnt/nfs-dir/app
  nfs-vol-db:
    name: nfs-vol-db
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.30,ro
      device: :/mnt/nfs-dir/initdb.d

services:
  web:
    container_name: poc-php-nginx
    image: nginx:1.27.1-alpine-slim
    restart: unless-stopped
    networks:
      - poc-php
    ports:
      - 8080:80
    volumes:
      - nfs-vol-nginx:/etc/nginx/conf.d
    depends_on:
      - php
    profiles:
      - build
  
  php:
    container_name: poc-php-8.3-fpm
    image: bitnami/php-fpm:8.3-debian-12
    restart: unless-stopped
    networks:
      - poc-php
    volumes:
      - nfs-vol-php:/srv
    depends_on:
      - db
    profiles:
      - build

  db:
    container_name: poc-php-mariadb
    image: mariadb:11.5
    restart: unless-stopped
    networks:
      - poc-php
    env_file:
      - .env
    volumes:
      - nfs-vol-db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql:Z
    profiles:
      - build
      - admin

  phpmyadmin:
    container_name: poc-php-pma
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: poc-php-mariadb
    env_file:
      - .env-pma
    networks:
      - poc-php
    ports:
      - "8085:80"
    depends_on:
      - db
    profiles:
      - admin

### JOBS

  cold-dump:
    image: alpine
    network_mode: none
    volumes:
      - db_data:/data
      - ./dump:/dump
    command: tar -czvf /dump/cold-dump.tar.gz /data
    profiles:
      - cold-dump
  


    

