## on prend un image de base de httpd
FROM httpd:2.4

## on documente notre image personnalisée
LABEL author="mlamamra"
LABEL created_at="2024-09-19"
LABEL created_at.year="2024"
LABEL stack="java"
LABEL stack.image="httpd"


## injecter une configuration princicpale personnalisée


## créer un dossier pour abriter les vhost httpd


## injecter le vhost de l'application java



## Déclarer les ports sur lesquels httpd va écouter



## spécifier la commande de lancement de l'image personnalisée