networks:
  poc-python:
    name: poc-python
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1


services:
  httpd:
    container_name: poc-python-httpd
    image: poc-python-httpd:0.1
    build:
      context: ./httpd
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - poc-python
    ports:
      - 8084:80
    depends_on:
      - app
    develop:
      watch:
        - action: sync+restart
          path: ./httpd/python_app.conf
          target: /usr/local/apache2/conf/sites/python_app.conf
  
  app:
    container_name: poc-python-app
    image: poc-python-app:0.1
    build:
      context: ./python
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - poc-python
    develop:
      watch:
        - action: sync+restart
          path: ./python/app/
          target: /var/local/app/
          ignore:
            - ./python/app/models
            - ./python/app/views
            - ./python/app/static
        - action: sync
          path: ./python/app/
          target: /var/local/app/
          ignore:
            - ./python/app/
            - ./python/app/requirements
            - ./python/app/bank
        - action: rebuild
          path: ./python/app/requirements.txt
