
networks:
  stack-java:
    name: stack-java
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  httpd:
    container_name: stack-java-httpd
    image: stack-java-httpd:0.1
    build:
      context: ./httpd
      dockerfile: Dockerfile
      # build sans cache
      # no_cache: true
    restart: unless-stopped
    networks:
      - stack-java
    ports:
      - 8081:80
    depends_on:
      - tomcat

  tomcat:
    container_name: stack-java-tomcat
    build:
      context: ./tomcat
      dockerfile: Dockerfile
      args:
        - TOMCAT_VERSION_FULL=${TOMCAT_VERSION_FULL:-9.0.95}
    image: stack-java-tomcat:0.1
    restart: unless-stopped
    networks:
      - stack-java
