## REM: par défaut: 
## si l'image est absente en local => build
## si l'image est présente en local => on l'utilise SAUF avec docker compose up --build -d
## docker compose build
## docker login ... && docker compose push


networks:
  stack-java:
    name: stack-java
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  httpd:
    container_name: stack-java-httpd
      # image: 192.168.1.30:443/stack-java-httpd:0.1
    image: stack-java-httpd:0.1
    build:
      context: ./httpd
      dockerfile: Dockerfile
      # build sans cache
      # no_cache: true
    restart: unless-stopped
    networks:
      - stack-java
    ports:
      - 8081:80
    depends_on:
      - tomcat
    develop:
      watch:
        - action: rebuild
          path: ./httpd/java_app.conf

  tomcat:
    container_name: stack-java-tomcat
    build:
      context: ./tomcat
      dockerfile: Dockerfile
      args:
        - TOMCAT_VERSION_FULL=${TOMCAT_VERSION_FULL:-9.0.95}
    # image: 192.168.1.30:443/stack-java-tomcat:0.1
    image: stack-java-tomcat:0.1
    restart: unless-stopped
    # volumes:
    #   - ./tomcat/fic:/opt/tomcat/fic
    networks:
      - stack-java
    develop:
      watch:
        - action: sync+restart
          path: ./tomcat/sample.war
          target: /opt/tomcat/webapps/sample.war
        # --watch ne fonctionne pas avec les bind mounts !!!
